[build]
builder = "paketobuildpacks/builder:base"

[deploy]
restartPolicyType = "on_failure"

[variables]
PYTHONUNBUFFERED = "1"
TZ = "Europe/Rome"
AUTOPILOT_TICK_SECONDS = "300"
LIVE_POLL_SECONDS = "75"
